language: node_js
node_js:
  - "0.12"
  - "1"
  - "2"
  - "3"
  - "4"
  - "5"
install: npm install
script: npm test
after_script: npm install coveralls && npm run coverage && cat ./coverage/lcov.info | coveralls
